name: Run API Tests

on:
  push:
    branches: [ api-tests ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout homework repository (this repo)
        uses: actions/checkout@v4
        with:
          path: api-tests

      - name: Clone test-service repository
        run: |
          git clone https://github.com/sun6r0/test-service.git test-service

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          cd api-tests
          pip install -r requirements.txt

      - name: Start services with Docker Compose
        run: |
          cd test-service
          docker compose up -d --build
          sleep 20  # даём время на запуск контейнеров и миграции

      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            if curl -s -f http://localhost:8080/api/time >/dev/null; then
              echo "API is ready"
              break
            fi
            echo "Waiting for API... ($i/30)"
            sleep 3
          done

      - name: Run tests
        env:
            BASE_URL: http://localhost:8080/api
        run: |
          cd api-tests
          python -m pytest tests/ -v -n 1 --alluredir=allure-results

      - run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
  
          curl -L -o allure.tgz https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          tar -xzf allure.tgz
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -sf /opt/allure/bin/allure /usr/bin/allure
          cd api-tests
          allure generate allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          force_orphan: true

      - name: Stop services
        if: always()
        run: |
          cd test-service
          docker compose down
